### ISSUE TITLE
READMEの言語一覧の表記を各言語にする

### ISSUE THREAD

**Issue by amotarao** [tokyo-metropolitan-gov/covid19#1103]
## 改善詳細 / Details of Improvement
>日本語 | English | Spanish | Korean | Chinese (Taiwan) | Chinese (Simplified) | Vietnamese
- 現在、日本語以外が英語で書かれている
- Korean: 한국어 など、各言語での表記に改める

**Comment by amotarao** [comment]
[みんなで逮捕されようプロジェクト](https://github.com/hamukazu/lets-get-arrested/blob/master/README.ja.md) という面白いプロジェクトがあって、相当数の翻訳がされているのですが、
>English | 日本語 | 한국어 | Bahasa Indonesia | Español | Deutsch | français | العربية | Português Brasileiro | Italiano | Nederlands | 简体中文 | 繁體中文 | Türkçe | বাংলা | Русский | Polski | Esperanto | Svenska | Magyar | Norsk | Bahasa Malaysia | ภาษาไทย | Tiếng Việt | Česky | ئۇيغۇر | Български | Հայերեն | فارسی | Ελληνικά

と、各言語で言語名が記載されています。

**Comment by amotarao** [comment]
このIssue では、現状の言語一覧において、英語にするか各言語にするかです。

現状は「Chinese (Taiwan)」となっているので、
そのまま現地の表記にするのであれば、「台灣華語」にするのがよさそうと思っています。

https://github.com/tokyo-metropolitan-gov/covid19/pull/1055#issuecomment-597420417
こちらコメントより下部で、繁體中文の表記について議論がされています。
「Chinese (Traditional)」や「繁體中文」にする議論はこのIssueとは別でやりましょう。

**Comment by Didichaoren** [comment]
@amotarao 
サイト側は文字をそれぞれ分別してサポートしたいと思います。
中国語世界範囲でも、書き方は二つのみがあります：

> 中文（简体）・中文（繁体）

あるいは

> 简体中文・繁體中文 

書き方と言い方を判明した方がいいです！日本でも日本語だけ各サイトが支持ています。わざと日本語（関西弁）していません。

以上です。

**Comment by amotarao** [comment]
@Didichaoren 
別の Issue を作成していただけませんか。
このIssueの目的は「English or NOT」です。

**Comment by ufcpp** [comment]
現地語がいいのではないでしょうか。
参考までに、
Google:
![image](https://user-images.githubusercontent.com/3760955/76382682-dfdbe680-639c-11ea-998f-58c902de22bd.png)

Microsoft:
![image](https://user-images.githubusercontent.com/3760955/76382701-e8342180-639c-11ea-8562-282d2298dc17.png)

AWS:
![image](https://user-images.githubusercontent.com/3760955/76382720-f71ad400-639c-11ea-9162-0d82aeb49bea.png)

**Comment by PichuChen** [comment]
Apple iOS:
![IMG_4018](https://user-images.githubusercontent.com/600238/76386183-c76ccb80-639e-11ea-9dc0-fdf1115ffbc5.PNG)
![IMG_4017](https://user-images.githubusercontent.com/600238/76386191-cb98e900-639e-11ea-8d11-e72d1011502d.PNG)

And the companies choose which language it supports depend on its resource, the market size and needs, so if the developers / contributors from Hong Kong thinks they need a README_ZH_HK.md, they can create a issue and send PR.

Because there are so many conflict and argues cases before, so I have chosen README_ZH_TW.md instead of README_ZH.md so developers / contributors outside TW can own their version.

Back to the topic, I think the label text on README.md just a casual note, no formally. It's a friendly entry for those who want to make contribution, so whatever is good, なんでもいいです.

**Comment by amotarao** [comment]
i18n 化で公開された言語名にして、一旦はよいかと思われます

<img width="239" alt="スクリーンショット 2020-03-13 1 32 55" src="https://user-images.githubusercontent.com/8909592/76543989-a3a6a400-64ca-11ea-80ad-12a5f6fc20a2.png">

**Comment by MaySoMusician** [comment]
@amotarao サイトの言語メニューの中国語の表記ですが、簡体字・繁体字は本来文字の種類の名前のはずですので、「中文」の表記はあったほうが良いかと思われます（「日本語」の代わりに「ひらがな・カタカナ」って表記されてしまっているイメージ）
（サイトの言語メニュー自体の修正issueは後ほど投げようと思っていました...）

**Comment by amotarao** [comment]
@MaySoMusician 確かにそうですね。

![image](https://user-images.githubusercontent.com/8909592/76545147-95f21e00-64cc-11ea-9f0f-567eb74914d0.png)
の 「字」を「中文」にしたものを このIssueの解決にしましょうか。

**Comment by MaySoMusician** [comment]
中文（簡体） or 簡体中文 かなと思います
（個人的には前者をよく見るのですが、どっちのパターンが相応しい表記なのかまでは自分は詳しくないので、他の方々の決定に一任します）

**Comment by amotarao** [comment]
確かに2パターンありました。

上のほうで貼って頂いてる画像も両パターンありますね 😓

**Comment by nuwaa** [comment]
@MaySoMusician @amotarao 
現状では見やすさの観点からひとまず、简体中文・繁體中文でよいかと思いますよ。
後にそれぞれの地域から翻訳できる方がジョインされた場合には、繁體中文(台灣)とか繁體中文(香港)と言う具合に分化していけばよろしいのではないかと。

**Comment by halsk** [comment]
@nuwaa さん、そうですね。そうしましょうか。

**Comment by nard-tech** [comment]
言語選択メニューの修正に関して issue を作成しました．
この issue と #1512，まとめて片付けてしまおうと思います．
