### ISSUE TITLE
From Tracing to Preemption

### ISSUE THREAD

**Issue by DavidStodolsky** [tokyo-metropolitan-gov/covid19#2317]
## 改善詳細 / Details of Improvement
- xxxx(できるだけ簡潔に/as concise as possible)

There are a number of application (app) assisted contact-tracing projects currently being developed in response to Covid-19. Their objective is to notify persons who may have been infected as quickly as possible so they can be tested or take other precautionary measures. However, with a proper information security architecture, it is possible to notify persons that they may be coming in contact with an infectious individual. This allows the person to preempt the contact or take precautions, such as wearing a mask.

http://cosmism.blogspot.com/2020/03/from-tracing-to-preemption.html

## 期待する見せ方・挙動 / Expected behavior
- xxxx(できるだけ簡潔に/as concise as possible)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by mcdmaster** [comment]
Hi @DavidStodolsky,

I understand your concern. I think though that the preemptive or preventive actions against COVID-19 must be guided by certain medical professionals in virus affection, not by ourselves.

Although I am convinced that the "hackers" who are participating in this are cool, they are not entirely medical professionals indeed and are unable to be responsible for such preemptive / preventive actions. Thank you for cooperation anyway.

**Comment by DavidStodolsky** [comment]
The person that may have been exposed makes the decision about being tested. It is other users that decide whether to avoid a person that has not reported for a test. These studies show that without instantaneous notification, the spread can't be controlled:

https://github.com/BDI-pathogens/covid-19_instant_tracing/blob/master/Policy%20forum%20-%20COVID-19%20containment%20by%20herd%20protection.pdf

**Comment by mcdmaster** [comment]
@DavidStodolsky,

I do not think that it will be able to be a general / common case, because individuals have different circumstances in every reason. In other words, we need to be on the same page that the capability of "testing" depends on various parameters e.g. numbers of hospitals / clinics which are capable of testing, numbers of patients affected by other diseases than COVID-19 etc. Anyway, we IT guys are not in a professional / responsible role to recommend testing to people in Tokyo even if we are thinking that testing is urgently necessary. That is my perspective in IT governance. Thanks anyway

**Comment by DavidStodolsky** [comment]
The proposal does not suggest that IT guys recommend testing. People interested in supporting a user-driven scientific approach can subscribe here: 

https://groups.io/g/MedicalEthics

**Comment by mcdmaster** [comment]
Hi @DavidStodolsky,

Yeah, this project is for informative purpose. In terms of scientific approach, I hope people like you introduced above would work by far better! Thanks anyway

**Comment by DavidStodolsky** [comment]
The info showing that current measures are not controlling the spread in Japan has apparently not reached the right people. We need resources to make progress.

**Comment by mcdmaster** [comment]
Hi @DavidStodolsky,

I wanted to tell you again that I agreed with you indeed.
I would like to ask you now whom you intend as "the right people" to have this project's output (information) reach. That is what I am unclear of, because I have seen so many web media and my SNS followers mentioning this site.
If the information delivery target gets clear, I think that we will be able to implement additional features accordingly.

**Comment by DavidStodolsky** [comment]
"the right people" are decision makers in government or companies that can help us put together a team of about ten people so we can release an app soon. Lacking that top level support, individuals that can contribute themselves are welcome to subscribe the list. We need software developers, project managers, etc. the most, but designers, marketers, translators, administrators, etc. could also play a role.

**Comment by DavidStodolsky** [comment]
@mcdmaster 

If you are qualified in project management, you could help us put together the team. We are awaiting a response from the Singapore government on a collaboration to enhance TraceTogether. However, getting even that running in Japan, would be an improvement over the current situation. Another potential project would be to start fund raising, etc. so we can independently release an app.

**Comment by mcdmaster** [comment]
If you mean "sponsorship", I wanted to say again that I totally agree with you. And I am convinced that the current project team is well-organized with SMEs inside Tokyo Metro office involved.

BTW, I need to let you know one thing that annoys us. Today I saw a comment of CPA who lives in Tokyo on my Facebook timeline that the surged (overshooting) numbers of "the infected" in Tokyo for a few days recently might be manipulated so that Governor Koike can easily emphasize the threat of COVID-19. Naturally, I told the CPA that he was misunderstanding with some prejudice accompanied.

Currently, I am working on this project as a contributor. If there is any opportunity in which I can work as a project manager, I will be fine with it. Thank you anyway.

**Comment by DavidStodolsky** [comment]
Not sure what you mean by "current project team is well-organized with SMEs inside Tokyo Metro office involved."

**Comment by MaySoMusician** [comment]
Hi @DavidStodolsky, thank you for sharing your ideas!
I understand what you said regarding "from Tracing to Preemption", but I'm still not sure what you want us to do (i.e. what are needed in our website)
Could you let me know specifically what we (of course including you too!) need do for the website?

**Comment by DavidStodolsky** [comment]
@mcdmaster

Re: "surged (overshooting) numbers of "the infected" in Tokyo for a few days recently might be manipulated so that Governor Koike can easily emphasize the threat of COVID-19."

Public confidence in political leadership is very low. People's confidence in authorities of all types has apparently reached an all-time low. Lack of confidence in authorities is one important factor in the stall in immunization rates in recent years (Y. Mahboubi, 2019). Harrington (2017) notes “We also discovered a staggering lack of confidence in leadership: 71% of survey respondents said government officials are not at all or somewhat credible….” Evens, Stoker, and Halupka (2018) found “compelling evidence of an increasing trust divide between government and citizens” and that “fewer than 41% of Australian citizens are satisfied with the way democracy works in Australia.”

This lack of confidence in authorities is one reason that an effective solution to the pandemic would best be user driven. It also requires that data security not be in the hands of a central authority. The proposed solution meets these requirements.

**Comment by mcdmaster** [comment]
Hey @DavidStodolsky,

Are you saying that you cannot understand this project's organization AFTER looking through ALL the artifacts and discussions done in this GitHub repository? In terms of open-source approach in this fast-changing circumstance, I can never show such criticism like yours because I deeply respect voluntary professionals, their achievements and skills. For me, this project looks like better than some commercial (successful) projects in which I participated before.

Anyway, as @MaySoMusician asks you, do let us know your idea more clearly to show what the additional / improved feature(s) you intended in a hands-on manner. Thanks.

**Comment by DavidStodolsky** [comment]
@mcdmaster

If you can help us with project management, a first step would be to set up a new project here - https://github.com/MyTurn-OpenSource
or maybe in a totally new repository to avoid any confusion due to the name.


"MyTurn-OpenSource" is currently devoted mostly to a dialogue management improvement that needs to be integrated with Jitsi or some other conferencing system. You can read of it here - https://cosmism.blogspot.com/2015/12/better-meetings-with-myturn.html

**Comment by mcdmaster** [comment]
Well noted. For sure, I will take a look. Thank you!

**Comment by MaySoMusician** [comment]
@mcdmaster 本issueの継続は必要そうでしょうか？ 彼が何を求めているのか未だつかめておらず...

**Comment by DavidStodolsky** [comment]
@MaySoMusician If you are referring to the current github pages as the "website", I have no suggestions. The point of my comments here is to alert people in Japan of our effort to combat Covid-19.

**Comment by mcdmaster** [comment]
@DavidStodolsky Sorry but please let me have discussion in Japanese w/ @MaySoMusician. Do feel free to translate it using third party tools like Google Translate.

@MaySoMusician さん、本件、クローズしてしまっても構わないと私は思います。お騒がせしてしまい、おそれ入ります。

私が最初の訳文で書いたところに沿い大雑把に端折って言えば、これまでのフォロー型、すなわち感染者数や犠牲者数といった実績値を追い求めるものから、先見的・予見的なものに転じていこうというアドバイスと思われます。おそらく、今後のオーバーシュート（私は、個人的にはこのコトバは嫌いです。アウトブレイクと言うべき）を慮ってのイシュー起票なのでしょう。
とはいえ、このプロジェクトに関する私の理解は、都から提供される情報をタイムリーかつ正確に、都に住む多くの層の人々にくまなく伝達するのがミッションである、というものです。
彼の主張の中には、検査を推進すべきという主旨の文言も見られました。とはいえ、これは既に各所でも言及されているように、場合によっては医療崩壊を招きかねないものです。
いずれにせよ、「現状の」本プロジェクトへの具体的なインプリ案が出てこない以上、これ以上ここで議論を続けても仕方がないでしょうね。

**Comment by DavidStodolsky** [comment]
@mcdmaster I have not looked through this GitHub repository in any detail. I am not normally using GitHub and I don't read Japanese. I actually needed help from a Japanese translator friend to even find this page where I could enter some information.

**Comment by mcdmaster** [comment]
@DavidStodolsky Do contribute to contents in Euro-American languages so that the quality of those non-Japanese artifacts can be better. Thank you in advance.

**Comment by MaySoMusician** [comment]
@DavidStodolsky  Could you tell me what components (e.g. graphs, tables, text) we add or change some of them for our [stopcovid19.metro.tokyo.lg.jp](https://stopcovid19.metro.tokyo.lg.jp/) website, if you have any opinions?

---

@mcdmaster ありがとうございます。
From Tracing to Preemptionの取り組みそのものは非常に意義があると私も感じています。ただ、それと本プロジェクト（東京都のサイト）とどう関係させたいのかな...と。単なる宣伝目的なら良くない前例（このGitHubのissueなら宣伝できる！）を作らないうちにクローズするのが適切かと思っております

**Comment by mcdmaster** [comment]
@MaySoMusician さん、From Tracing to Preemption の取り組みについては、私が彼の repo に参加するということでいったん決着した格好にしましょう。おっしゃるように、私もここを宣伝の場にしたくはありません。クローズをお願いしてもよろしいでしょうか

**Comment by MaySoMusician** [comment]
ありがとうございます！ お手数おかけします...
