### ISSUE TITLE
「各保健所にご相談ください」と「37.5℃」での体温の表記を「37.5℃」に統一する

### ISSUE THREAD

**Issue by masanori1102** [tokyo-metropolitan-gov/covid19#2757]
## 改善詳細 / Details of Improvement
「各保健所にご相談ください」と「37.5℃」での体温の表記を「37.5℃」に統一する。
以下の言語では、℃と記載されていない。
- `assets/locales/en.json`: 37.5 degrees
- `assets/locales/ja.json`: 37.5度
- `assets/locales/ko.json`: 37.5도
- `assets/locales/zh_TW.json`: 37.5度

## スクリーンショット / Screenshot
なし

## 期待する見せ方・挙動 / Expected behavior
言語を問わず、37.5℃と表記される

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by yanoyuki** [comment]
こちら着手します

**Comment by masanori1102** [comment]
「37.5 degreeで、華氏37.5度(摂氏3.06度)かよ！」と誤読しないように、「摂氏で37.5度ですよ」ということをわかりやすく示す為の変更です。

**Comment by PichuChen** [comment]
Hello there,

Because we have move translation works to [transifex](https://www.transifex.com/stopcovid19-tokyo/stopcovid19tokyo/translate/#zh_TW/$/283234978?q=text%3A%E5%90%84%E4%BF%9D%E5%81%A5%E6%89%80%E3%81%AB%E3%81%94%E7%9B%B8%E8%AB%87%E3%81%8F%E3%81%A0%E3%81%95%E3%81%84), so directly editing 
`assets/locales/en.json`
`assets/locales/ko.json`
`assets/locales/zh_TW.json`

will be overwritten, 

Just edit `assets/locales/ja.json`, and transifex will sync it to translate table automatically.

**Comment by MaySoMusician** [comment]
@PichuChen Thank you for your additional comments! I also referred to that in https://github.com/tokyo-metropolitan-gov/covid19/pull/2759#issuecomment-607642807

**Comment by yanoyuki** [comment]
transifexの仕様を理解しておらずお手数おかけしました！

こちらは、 `assets/locales/ja.json`のみの編集とし、残りのファイルについては編集差分を戻します。
