### ISSUE TITLE
A misspelling and misused word on the site

### ISSUE THREAD

**Issue by davidsiaw** [tokyo-metropolitan-gov/covid19#5393]
## 改善詳細 / Details of Improvement
A link on the main navigational bar on the left side is mispelled (see screenshot)

Also there is a better word for "ナビ", in English the word for a webpage that functions as a gateway to a variety of other pages is called a "Portal".

It is better to change the link to "Tokyo COVID-19 INFORMATION PORTAL"

With this change, people who read and speak English natively will more easily notice the link and find the information they need.

## スクリーンショット / Screenshot
<img width="1116" alt="スクリーンショット 2020-09-09 14 33 55" src="https://user-images.githubusercontent.com/874280/92558517-ae8b9700-f2a9-11ea-9dcd-1c41a6f3c9cb.png">

## 動作環境・ブラウザ / Environment
All environments
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

Thank you for conducting this informational campaign online and for all the work you have done.

**Comment by MaySoMusician** [comment]
Thanks for creating the issue! We are also managing our translation project on Transifex, and due to integration with this, we are forced not to make any change to `assets/locales/en.json` on GitHub (to other language files as well), which will be overwritten when the changes made on Transfiex.

Our Transifex project is [here](https://www.transifex.com/stopcovid19-tokyo/stopcovid19tokyo/dashboard/), so could you visit the page and change the translation you want to?

And as for "ナビ", the linked page is out of our project, that means "東京都 新型コロナウイルス感染症 支援情報ナビ" is a proper noun which we probably should confirm the translation of.  We'll keep you updated on this.

**Comment by MaySoMusician** [comment]
@davidsiaw According to the Tokyo Metropolitan Government, the translation is “Tokyo COVID-19 Support Information Navigation.” We have committed the change to the source code.

**Comment by davidsiaw** [comment]
Sounds good. Looks like you guys have made all the necessary changes so I'll close this issue.
