### ISSUE TITLE
Open Source Helps!

### ISSUE THREAD

**Issue by WeileiZeng** [tokyo-metropolitan-gov/covid19#648]
Thanks for your work to help the people in need! Your site has been added! I currently maintain the OpenSourceWuhan page, which collects all open source projects related to COVID-19, including maps, data, news, api, analysis, medical and supply information, etc. Please share to anyone who might need the information in the list, or will possibly contribute to some of those projects. You are also welcome to recommend more projects.

https://weileizeng.github.io/OpenSourceWuhan/world

Cheers!

**Comment by mcdmaster** [comment]
Hey Weilei,,

Thanks for the comment. I suppose that this project has contribution rooms for you guys, for instance:
* Showing periodic comparison chart (graph) of numbers of patients/victims b/w areas in Wuhan and Tokyo Met;
* Reviewing our i18n text, especially in Simplified Chinese;
* And many more!

Anyway, if we can collaborate to survive this coronavirus crisis, we both can be happy and, for sure, we both can be friends! Thanks again.

**Comment by WeileiZeng** [comment]
> Hey Weilei,,
> 
> Thanks for the comment. I suppose that this project has contribution rooms for you guys, for instance:
> 
> * Showing periodic comparison chart (graph) of numbers of patients/victims b/w areas in Wuhan and Tokyo Met;
> * Reviewing our i18n text, especially in Simplified Chinese;
> * And many more!
> 
> Anyway, if we can collaborate to survive this coronavirus crisis, we both can be happy and, for sure, we both can be friends! Thanks again.

Thanks! Your suggestion sounds very good! I will help to spread the need. (The goal of my site is to trigger more collaborations)

Meanwhile, what is i18n text?

**Comment by mcdmaster** [comment]
Weilei,

Thanks for the quick turnaround! Basically, you can find open issues via this project's "Issues" page.
I knew, however, that you guys are restricted to use an external & useful translation tool e.g. Google Translate.
If you could, you would be able to see the Issues flawlessly even if they are entirely written in Japanese...I hope you could find alternatives for translation purpose.

The word i18n stands for "internationalization", which simply means turning a web site for the use of multilingual (+ multinational and multicultural) people. Look the word, and you can notice that there are 18 characters b/w the first "i" and the last "n" :)

Anyway, I recommend you to once close this Issue and raise another (or more) Issue(s) particularly so that the Issue can be more specific and practically enabled to deal with. Thanks again for cooperation in advance.

**Comment by WeileiZeng** [comment]
Thanks! Learn a new word.

I saw many [i18n] issues opened. I will promote these in Chinese-based communities.

**Comment by halsk** [comment]
Thank you
