### ISSUE TITLE
7-day average in monitoring_items.json not updated

### ISSUE THREAD

**Issue by aborza-c** [tokyo-metropolitan-gov/covid19#7625]
## 起こっている問題 / The Problem

`monitoring_items.json` has same data since 2022-10-27.

https://github.com/tokyo-metropolitan-gov/covid19/blob/development/data/monitoring_items.json#L14
`"(1)新規陽性者数": 3371.6`

## スクリーンショット / Screenshot

<img width="581" alt="Screen Shot 2022-11-02 at 10 12 05" src="https://user-images.githubusercontent.com/67132522/199371524-5a6144af-61f1-4aad-b42d-40711cdff548.png">

## 期待する見せ方・挙動 / Expected Behavior

7-day average should be reported correctly.

## 起こっている問題の再現手段 / Steps to Reproduce

1. Look at https://github.com/tokyo-metropolitan-gov/covid19/blob/development/data/monitoring_items.json
2. Verify the correct  date.
3. See that 7-day average reported is the same value every day.

## 動作環境・ブラウザ / Environment

Any.

**Comment by kaizumaki** [comment]
@aborza-c Thank you for the issue!
monitoring_items.json#L14-L24 has not entered data since 10/28/2022.
https://github.com/tokyo-metropolitan-gov/covid19/blob/da4b8a4734e5322980a64378f2fc803aeeafe069/data/monitoring_items.json#L14-L24
Instead, we did the following modifications.
#7588
I know this is confusing, so monitoring_items.json#L14-L24 should output null or delete the key.
